### ISSUE TITLE
About problems encountered on the server

### ISSUE THREAD

**Issue by JIANG-1102** [SC-SGS/PLSSVM#31] opened 2023-02-05 09:50 UTC
Recently, I tried to run this project on the server, but due to my limited ability, the problem encountered is really unsolvable, so I want to ask you.
This project will install three python libraries when cmake, namely: cxxopts, fast_float, fmt. But when I was doing cmake, I always got a prompt that module creation failed. So, I tried to download manually, and even though the download was successful, it still failed when performing cmake. Probably the reason why the server doesn't connect to GitHub, I guess.

**Comment by breyerml** [comment] 2023-02-06 12:46
That's correct and an error or restriction from our side. 
The problem is the following logic (example for cxxopts):
```cmake
find_package(cxxopts 3.0.0 QUIET)
if (cxxopts_FOUND)
    message(STATUS "Found package cxxopts.")
else ()
    message(STATUS "Couldn't find package cxxopts. Building from source ...")
    set(PLSSVM_cxxopts_VERSION v3.0.0)
    # fetch command line parser library cxxopts
    FetchContent_Declare(cxxopts
        ...
    )
endif ()
```
**If** cxxopts can't be found using the find_package call, it tries to install it from source using git (which obviously fails if no connection to GitHub can be established which is the case for many large compute clusters). The problem is that the header-only libraries do **not** support the ge calls. Hence, it **always** tries to install the libraries from GitHub.

I've committed ([`82587ba`](https://github.com/SC-SGS/PLSSVM/commit/82587ba437d9c73ad6c7333293cd18cf1b154ba7)) some changes to a new branch called [`find_package_fix`](https://github.com/SC-SGS/PLSSVM/tree/find_package_fix). 
I've created custom find modules for the three header-only libraries cxxopts, fast_float, and igor (the last one is a new dependency from the current develop branch). It should now work if you provide the respective include directories as environment variables before a call to cmake. Not that fmt does already support the find_package calls if everything was set up correctly.

Here are the steps by which I was able to compile our PLSSVM library on a system that does not allow a connection to GitHub:

1. Install dependencies:
  - Download the [`cxxopts`](https://github.com/jarro2783/cxxopts) source and copy it to the target system.
  - Set the variable `cxxopts_INCLUDE_DIR` to the respective include directory.
  - Download the [`fast_float`](https://github.com/fastfloat/fast_float) source and copy it to the target system.
  - Set the variable `fast_float_INCLUDE_DIR` to the respective include directory.
  - Download the [`igor`](https://github.com/bluescarni/igor) source and copy it to the target system.
  - Set the variable `igor_INCLUDE_DIR` to the respective include directory.
  - Install [`{fmt}`](https://github.com/fmtlib/fmt) using [`spack`](https://github.com/spack/spack):
    - Install `spack` on the target system (if not already installed).
    - Source the respective file under `spack/share/spack`, e.g., for bash or zsh: `source ${HOME}/spack/share/spack/setup-env.sh` (if `spack` is installed in the `${HOME}` directory, otherwise add the correct path).
    - Install {fmt} using: `spack install fmt`.
    - Load the installed fmt library: `spack load fmt`
2. Download the PLSSVM source from the [`find_package_fix`](https://github.com/SC-SGS/PLSSVM/tree/find_package_fix) branch, create a build folder, and move to it.
3. If Python3 and the necessary Python packages are installed, simply type `cmake ..`.
If **no** Python3 is installed or some packages are missing and cannot be installed, you have to manually specify the `PLSSVM_TARGET_PLATFORMS` **and** disable the tests. An example invocation for an NVIDIA A100 GPU and a CPU then looks like this: 
`cmake -DPLSSVM_TARGET_PLATFORMS="cpu;nvidia:sm_80" -DPLSSVM_ENABLE_TESTING=OFF ..`
4. Compile the PLSSVM library using `make`.

If the problem still persists, please let us know including the corresponding error message.

**Comment by breyerml** [comment] 2023-02-10 11:23
The fix has been merged into the `develop` branch.

**Comment by breyerml** [comment] 2023-02-21 08:51
Closing this issue in a few days because of no response.

**Closed** 2023-03-10 07:52 UTC
Labels: bug
